const products = [
  {
    id: 1,
    name: "Apple",
    category: "fruits",
    price: 120,
    image: "https://i.imgur.com/O1RmSjo.jpg",
  },
  {
    id: 2,
    name: "Banana",
    category: "fruits",
    price: 40,
    image: "https://i.imgur.com/w1NOe9B.jpg",
  },
  {
    id: 3,
    name: "Tomato",
    category: "vegetables",
    price: 30,
    image: "https://i.imgur.com/fVJ5i3T.jpg",
  },
  {
    id: 4,
    name: "Potato",
    category: "vegetables",
    price: 25,
    image: "https://i.imgur.com/vf3bNQB.jpg",
  },
  {
    id: 5,
    name: "Milk (1L)",
    category: "dairy",
    price: 55,
    image: "https://i.imgur.com/HGpOQyM.jpg",
  },
  {
    id: 6,
    name: "Curd",
    category: "dairy",
    price: 40,
    image: "https://i.imgur.com/HXxMgNh.jpg",
  },
  {
    id: 7,
    name: "Bread",
    category: "bakery",
    price: 30,
    image: "https://i.imgur.com/9V94Rp0.jpg",
  },
  {
    id: 8,
    name: "Biscuits",
    category: "packaged",
    price: 20,
    image: "https://i.imgur.com/gE0HKeS.jpg",
  },
  {
    id: 9,
    name: "Shampoo",
    category: "personal",
    price: 85,
    image: "https://i.imgur.com/utUJXEl.jpg",
  },
  {
    id: 10,
    name: "Dishwash Liquid",
    category: "household",
    price: 75,
    image: "https://i.imgur.com/Mx1fT8M.jpg",
  },
  {
    id: 11,
    name: "Turmeric Powder",
    category: "spices",
    price: 60,
    image: "https://i.imgur.com/Gp1RE7U.jpg",
  },
  {
    id: 12,
    name: "Wheat Flour (1kg)",
    category: "grains",
    price: 45,
    image: "https://i.imgur.com/I9UIqJk.jpg",
  },
  {
    id: 13,
    name: "Rice (1kg)",
    category: "grains",
    price: 55,
    image: "https://i.imgur.com/xkj2f7F.jpg",
  },
  {
    id: 14,
    name: "Tea Powder",
    category: "beverages",
    price: 100,
    image: "https://i.imgur.com/JmCzWRX.jpg",
  },
  {
    id: 15,
    name: "Cold Drink",
    category: "beverages",
    price: 35,
    image: "https://i.imgur.com/LGL8b7B.jpg",
  }
];

export default products;
